import test from 'node:test';
import assert from 'node:assert/strict';

import { OPENAPI_PATH, readJson, resolveParameters } from '../../scripts/lib/quality-gates.mjs';
import {
  getContract,
  getPublicRoute,
  getService
} from '../../services/internal-contracts/src/index.mjs';
import { mongodbDataAdapterPort } from '../../services/adapters/src/mongodb-data-api.mjs';

test('mongo data API service contracts and adapter capability baseline are published', () => {
  const mongoDataRequest = getContract('mongo_data_request');
  const mongoDataResult = getContract('mongo_data_result');
  const controlApi = getService('control_api');
  const provisioning = getService('provisioning_orchestrator');

  assert.ok(controlApi.outbound_contracts.includes('mongo_data_request'));
  assert.ok(provisioning.inbound_contracts.includes('mongo_data_request'));
  assert.ok(provisioning.outbound_contracts.includes('mongo_data_result'));
  assert.equal(mongoDataRequest.owner, 'control_api');
  assert.equal(mongoDataResult.owner, 'provisioning_orchestrator');
  assert.ok(mongoDataRequest.required_fields.includes('tenant_scope'));
  assert.ok(mongoDataRequest.required_fields.includes('filters'));
  assert.ok(mongoDataRequest.required_fields.includes('projection'));
  assert.ok(mongoDataRequest.required_fields.includes('sort'));
  assert.ok(mongoDataRequest.required_fields.includes('page'));
  assert.ok(mongoDataRequest.required_fields.includes('bulk_limits'));
  assert.ok(mongoDataRequest.required_fields.includes('collection_validation'));
  assert.ok(mongoDataRequest.required_fields.includes('aggregation'));
  assert.ok(mongoDataRequest.required_fields.includes('transfer'));
  assert.ok(mongoDataRequest.required_fields.includes('transaction'));
  assert.ok(mongoDataRequest.required_fields.includes('change_stream'));
  assert.ok(mongoDataRequest.required_fields.includes('capability_compatibility'));
  assert.ok(mongoDataRequest.required_fields.includes('trace_context'));
  assert.ok(mongoDataRequest.required_fields.includes('plan_policy'));
  assert.ok(mongoDataResult.required_fields.includes('documents'));
  assert.ok(mongoDataResult.required_fields.includes('counts'));
  assert.ok(mongoDataResult.required_fields.includes('page'));
  assert.ok(mongoDataResult.required_fields.includes('tenant_scope'));
  assert.ok(mongoDataResult.required_fields.includes('bulk_summary'));
  assert.ok(mongoDataResult.required_fields.includes('validation_summary'));
  assert.ok(mongoDataResult.required_fields.includes('aggregation_summary'));
  assert.ok(mongoDataResult.required_fields.includes('transfer_summary'));
  assert.ok(mongoDataResult.required_fields.includes('transaction_summary'));
  assert.ok(mongoDataResult.required_fields.includes('change_stream'));
  assert.ok(mongoDataResult.required_fields.includes('capability_compatibility'));
  assert.ok(mongoDataResult.required_fields.includes('trace_context'));
  assert.ok(mongoDataResult.required_fields.includes('audit_record_id'));
  assert.ok(mongodbDataAdapterPort.capabilities.includes('mongo_data_query'));
  assert.ok(mongodbDataAdapterPort.capabilities.includes('mongo_data_insert'));
  assert.ok(mongodbDataAdapterPort.capabilities.includes('mongo_data_update'));
  assert.ok(mongodbDataAdapterPort.capabilities.includes('mongo_data_replace'));
  assert.ok(mongodbDataAdapterPort.capabilities.includes('mongo_data_delete'));
  assert.ok(mongodbDataAdapterPort.capabilities.includes('mongo_data_bulk_write'));
  assert.ok(mongodbDataAdapterPort.capabilities.includes('mongo_data_aggregate'));
  assert.ok(mongodbDataAdapterPort.capabilities.includes('mongo_data_import'));
  assert.ok(mongodbDataAdapterPort.capabilities.includes('mongo_data_export'));
  assert.ok(mongodbDataAdapterPort.capabilities.includes('mongo_data_transaction'));
  assert.ok(mongodbDataAdapterPort.capabilities.includes('mongo_data_change_stream'));
});

test('mongo data API public routes publish CRUD/query, transfer, transaction, change-stream, and scoped-credential metadata', () => {
  const document = readJson(OPENAPI_PATH);
  const listDocumentsRoute = getPublicRoute('listMongoDataDocuments');
  const createDocumentRoute = getPublicRoute('createMongoDataDocument');
  const getDocumentRoute = getPublicRoute('getMongoDataDocument');
  const updateDocumentRoute = getPublicRoute('updateMongoDataDocument');
  const replaceDocumentRoute = getPublicRoute('replaceMongoDataDocument');
  const deleteDocumentRoute = getPublicRoute('deleteMongoDataDocument');
  const bulkWriteRoute = getPublicRoute('bulkWriteMongoDataDocuments');
  const aggregateRoute = getPublicRoute('aggregateMongoDataDocuments');
  const importRoute = getPublicRoute('importMongoDataDocuments');
  const exportRoute = getPublicRoute('exportMongoDataDocuments');
  const transactionRoute = getPublicRoute('executeMongoDataTransaction');
  const changeStreamRoute = getPublicRoute('createMongoDataChangeStream');
  const listCredentialsRoute = getPublicRoute('listMongoDataCredentials');
  const createCredentialRoute = getPublicRoute('createMongoDataCredential');
  const getCredentialRoute = getPublicRoute('getMongoDataCredential');
  const revokeCredentialRoute = getPublicRoute('revokeMongoDataCredential');

  const listOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/collections/{collectionName}/documents'].get;
  const createOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/collections/{collectionName}/documents'].post;
  const getOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/collections/{collectionName}/documents/{documentId}'].get;
  const updateOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/collections/{collectionName}/documents/{documentId}'].patch;
  const replaceOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/collections/{collectionName}/documents/{documentId}'].put;
  const bulkOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/collections/{collectionName}/bulk/write'].post;
  const aggregateOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/collections/{collectionName}/aggregations'].post;
  const importOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/collections/{collectionName}/imports'].post;
  const exportOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/collections/{collectionName}/exports'].post;
  const transactionOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/transactions'].post;
  const changeStreamOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/collections/{collectionName}/change-streams'].post;
  const listCredentialsOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/credentials'].get;
  const createCredentialOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/credentials'].post;
  const getCredentialOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/credentials/{credentialId}'].get;
  const revokeCredentialOperation = document.paths['/v1/mongo/workspaces/{workspaceId}/data/{databaseName}/credentials/{credentialId}'].delete;
  const listParameters = resolveParameters(document, listOperation);
  const createParameters = resolveParameters(document, createOperation);
  const getParameters = resolveParameters(document, getOperation);
  const updateParameters = resolveParameters(document, updateOperation);
  const replaceParameters = resolveParameters(document, replaceOperation);
  const bulkParameters = resolveParameters(document, bulkOperation);
  const aggregateParameters = resolveParameters(document, aggregateOperation);
  const importParameters = resolveParameters(document, importOperation);
  const exportParameters = resolveParameters(document, exportOperation);
  const transactionParameters = resolveParameters(document, transactionOperation);
  const changeStreamParameters = resolveParameters(document, changeStreamOperation);
  const createCredentialParameters = resolveParameters(document, createCredentialOperation);
  const getCredentialParameters = resolveParameters(document, getCredentialOperation);
  const revokeCredentialParameters = resolveParameters(document, revokeCredentialOperation);

  assert.equal(listDocumentsRoute.family, 'mongo');
  assert.equal(listDocumentsRoute.resourceType, 'mongo_data_documents');
  assert.equal(listDocumentsRoute.gatewayQosProfile, 'provisioning');
  assert.equal(createDocumentRoute.resourceType, 'mongo_data_documents');
  assert.equal(createDocumentRoute.supportsIdempotencyKey, true);
  assert.equal(getDocumentRoute.resourceType, 'mongo_data_document');
  assert.equal(updateDocumentRoute.supportsIdempotencyKey, true);
  assert.equal(replaceDocumentRoute.supportsIdempotencyKey, true);
  assert.equal(deleteDocumentRoute.supportsIdempotencyKey, true);
  assert.equal(bulkWriteRoute.resourceType, 'mongo_data_bulk');
  assert.equal(bulkWriteRoute.supportsIdempotencyKey, true);
  assert.equal(aggregateRoute.resourceType, 'mongo_data_aggregation');
  assert.equal(importRoute.resourceType, 'mongo_data_import');
  assert.equal(importRoute.supportsIdempotencyKey, true);
  assert.equal(exportRoute.resourceType, 'mongo_data_export');
  assert.equal(transactionRoute.resourceType, 'mongo_data_transaction');
  assert.equal(transactionRoute.supportsIdempotencyKey, true);
  assert.equal(changeStreamRoute.resourceType, 'mongo_data_change_stream');
  assert.equal(changeStreamRoute.supportsIdempotencyKey, true);
  assert.equal(listCredentialsRoute.resourceType, 'mongo_data_credential');
  assert.equal(createCredentialRoute.supportsIdempotencyKey, true);
  assert.equal(getCredentialRoute.resourceType, 'mongo_data_credential');
  assert.equal(revokeCredentialRoute.supportsIdempotencyKey, true);

  assert.equal(listOperation['x-resource-type'], 'mongo_data_documents');
  assert.equal(createOperation['x-resource-type'], 'mongo_data_documents');
  assert.equal(getOperation['x-resource-type'], 'mongo_data_document');
  assert.equal(updateOperation['x-resource-type'], 'mongo_data_document');
  assert.equal(replaceOperation['x-resource-type'], 'mongo_data_document');
  assert.equal(bulkOperation['x-resource-type'], 'mongo_data_bulk');
  assert.equal(aggregateOperation['x-resource-type'], 'mongo_data_aggregation');
  assert.equal(importOperation['x-resource-type'], 'mongo_data_import');
  assert.equal(exportOperation['x-resource-type'], 'mongo_data_export');
  assert.equal(transactionOperation['x-resource-type'], 'mongo_data_transaction');
  assert.equal(changeStreamOperation['x-resource-type'], 'mongo_data_change_stream');
  assert.equal(listCredentialsOperation['x-resource-type'], 'mongo_data_credential');
  assert.equal(createCredentialOperation['x-resource-type'], 'mongo_data_credential');
  assert.equal(getCredentialOperation['x-resource-type'], 'mongo_data_credential');
  assert.equal(revokeCredentialOperation['x-resource-type'], 'mongo_data_credential');

  assert.equal(listParameters.some((parameter) => parameter.name === 'filter'), true);
  assert.equal(listParameters.some((parameter) => parameter.name === 'projection'), true);
  assert.equal(listParameters.some((parameter) => parameter.name === 'sort'), true);
  assert.equal(listParameters.some((parameter) => parameter.name === 'page[size]'), true);
  assert.equal(createParameters.some((parameter) => parameter.name === 'Idempotency-Key'), true);
  assert.equal(getParameters.some((parameter) => parameter.name === 'documentId'), true);
  assert.equal(updateParameters.some((parameter) => parameter.name === 'Idempotency-Key'), true);
  assert.equal(replaceParameters.some((parameter) => parameter.name === 'Idempotency-Key'), true);
  assert.equal(bulkParameters.some((parameter) => parameter.name === 'Idempotency-Key'), true);
  assert.equal(aggregateParameters.some((parameter) => parameter.name === 'collectionName'), true);
  assert.equal(importParameters.some((parameter) => parameter.name === 'Idempotency-Key'), true);
  assert.equal(exportParameters.some((parameter) => parameter.name === 'collectionName'), true);
  assert.equal(transactionParameters.some((parameter) => parameter.name === 'Idempotency-Key'), true);
  assert.equal(changeStreamParameters.some((parameter) => parameter.name === 'Idempotency-Key'), true);
  assert.equal(createCredentialParameters.some((parameter) => parameter.name === 'Idempotency-Key'), true);
  assert.equal(getCredentialParameters.some((parameter) => parameter.name === 'credentialId'), true);
  assert.equal(revokeCredentialParameters.some((parameter) => parameter.name === 'Idempotency-Key'), true);

  assert.ok(document.components.schemas.MongoDataDocumentCollection);
  assert.ok(document.components.schemas.MongoDataDocumentEnvelope);
  assert.ok(document.components.schemas.MongoDataInsertRequest);
  assert.ok(document.components.schemas.MongoDataPatchRequest);
  assert.ok(document.components.schemas.MongoDataReplaceRequest);
  assert.ok(document.components.schemas.MongoDataMutationResult);
  assert.ok(document.components.schemas.MongoDataBulkWriteRequest);
  assert.ok(document.components.schemas.MongoDataBulkMutationResult);
  assert.ok(document.components.schemas.MongoDataBulkWriteOperation);
  assert.ok(document.components.schemas.MongoDataTenantScope);
  assert.ok(document.components.schemas.MongoDataValidationSummary);
  assert.ok(document.components.schemas.MongoDataTraceContext);
  assert.ok(document.components.schemas.MongoDataAuditSummary);
  assert.ok(document.components.schemas.MongoDataFeatureCompatibility);
  assert.ok(document.components.schemas.MongoDataAggregationRequest);
  assert.ok(document.components.schemas.MongoDataAggregationResult);
  assert.ok(document.components.schemas.MongoDataImportRequest);
  assert.ok(document.components.schemas.MongoDataImportResult);
  assert.ok(document.components.schemas.MongoDataExportRequest);
  assert.ok(document.components.schemas.MongoDataExportResult);
  assert.ok(document.components.schemas.MongoDataTransactionRequest);
  assert.ok(document.components.schemas.MongoDataTransactionResult);
  assert.ok(document.components.schemas.MongoDataChangeStreamRequest);
  assert.ok(document.components.schemas.MongoDataChangeStreamResult);
  assert.ok(document.components.schemas.MongoDataCredentialScope);
  assert.ok(document.components.schemas.MongoDataCredentialCreateRequest);
  assert.ok(document.components.schemas.MongoDataCredentialRecord);
  assert.ok(document.components.schemas.MongoDataCredentialCollection);
  assert.ok(document.components.schemas.MongoDataCredentialSecretEnvelope);

  assert.equal(document.components.schemas.MongoDataTraceContext.properties.workspaceId.type, 'string');
  assert.equal(document.components.schemas.MongoDataMutationResult.required.includes('auditRecordId'), true);
  assert.equal(document.components.schemas.MongoDataTransactionResult.required.includes('auditSummary'), true);
});
