import { ConsolePageState } from '@/components/console/ConsolePageState'
import { WizardShell } from '@/components/console/wizards/WizardShell'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select } from '@/components/ui/select'
import { useConsoleContext } from '@/lib/console-context'
import { createValidation, submitWizardRequest, useWizardPermissionCheck, type WizardStepProps } from '@/lib/console-wizards'

interface IamClientData { workspaceId: string; clientType: string; clientId: string; redirectUris: string; scopes: string[] }
function WorkspaceStep({ data }: WizardStepProps<IamClientData>) { return <div><Label>Workspace</Label><p className="mt-2 text-sm">{data.workspaceId || 'Sin workspace activo'}</p></div> }
function TypeStep({ data, onChange, validation }: WizardStepProps<IamClientData>) { return <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="client-type">Tipo</Label><Select id="client-type" value={data.clientType ?? ''} onChange={(e) => onChange({ clientType: e.target.value })}><option value="">Selecciona</option><option value="public">public</option><option value="confidential">confidential</option><option value="service_account">service_account</option></Select></div><div className="space-y-2"><Label htmlFor="client-id">Client ID</Label><Input id="client-id" value={data.clientId ?? ''} onChange={(e) => onChange({ clientId: e.target.value })} />{validation.fieldErrors.clientId ? <p className="text-sm text-destructive">{validation.fieldErrors.clientId}</p> : null}</div></div> }
function RedirectStep({ data, onChange, validation }: WizardStepProps<IamClientData>) { return <div className="space-y-2"><Label htmlFor="redirect-uris">Redirect URIs</Label><Input id="redirect-uris" value={data.redirectUris ?? ''} onChange={(e) => onChange({ redirectUris: e.target.value })} placeholder="https://app.example/callback" />{validation.fieldErrors.redirectUris ? <p className="text-sm text-destructive">{validation.fieldErrors.redirectUris}</p> : null}</div> }
function ScopeStep({ data, onChange }: WizardStepProps<IamClientData>) { const scopes = ['openid','profile','email']; return <div className="space-y-2"><Label>Scopes</Label>{scopes.map((scope) => <label key={scope} className="flex items-center gap-2 text-sm"><Checkbox checked={(data.scopes ?? []).includes(scope)} onChange={(e) => onChange({ scopes: e.currentTarget.checked ? [...(data.scopes ?? []), scope] : (data.scopes ?? []).filter((item) => item !== scope) })} />{scope}</label>)}</div> }
export function CreateIamClientWizard({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
 const { activeWorkspaceId } = useConsoleContext(); const permission = useWizardPermissionCheck('manage_iam'); if (!permission.allowed) return open ? <ConsolePageState kind="blocked" title="Acceso bloqueado" description={permission.reason ?? 'No permitido.'} /> : null; return <WizardShell<IamClientData> open={open} onOpenChange={onOpenChange} title="Nuevo cliente IAM" description="Alta guiada de cliente IAM." context={{ tenantId: null, workspaceId: activeWorkspaceId, principalRoles: [] }} initialData={{ workspaceId: activeWorkspaceId ?? '', scopes: [] }} steps={[{ id: 'workspace', label: 'Workspace', component: WorkspaceStep, validate: (data) => createValidation(!data.workspaceId ? { workspaceId: 'Selecciona un workspace.' } : {}) },{ id: 'type', label: 'Tipo', component: TypeStep, validate: (data) => createValidation(!data.clientId?.trim() ? { clientId: 'El clientId es obligatorio.' } : {}) },{ id: 'redirects', label: 'Redirect URIs', component: RedirectStep, validate: (data) => createValidation(data.clientType !== 'service_account' && !(data.redirectUris ?? '').includes('://') ? { redirectUris: 'Introduce al menos una URI válida.' } : {}) },{ id: 'scopes', label: 'Scopes', component: ScopeStep, validate: () => createValidation() }]} buildSummary={(data) => [{ label: 'Workspace', value: data.workspaceId ?? '' },{ label: 'Tipo', value: data.clientType ?? '' },{ label: 'Client ID', value: data.clientId ?? '' },{ label: 'Redirect URIs', value: data.redirectUris ?? '' },{ label: 'Scopes', value: (data.scopes ?? []).join(', ') }]} onSubmit={async (data) => { const response = await submitWizardRequest<{ iamClientId: string }>(`/v1/workspaces/${data.workspaceId ?? activeWorkspaceId}/iam/clients`, { clientType: data.clientType ?? 'public', clientId: data.clientId ?? '', redirectUris: data.clientType === 'service_account' ? [] : String(data.redirectUris ?? '').split(',').map((item) => item.trim()).filter(Boolean), scopes: data.scopes ?? [], permissions: [] }); return { resourceId: response.iamClientId, resourceUrl: '/console/auth' } }} />
}
