import { ConsolePageState } from '@/components/console/ConsolePageState'
import { WizardShell } from '@/components/console/wizards/WizardShell'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { useConsoleContext } from '@/lib/console-context'
import { createValidation, submitWizardRequest, useWizardPermissionCheck, useWizardQuotaCheck, type WizardStepProps } from '@/lib/console-wizards'

interface InviteData { workspaceId: string; email: string; role: string; message: string }
const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
function WorkspaceStep({ data }: WizardStepProps<InviteData>) { return <div><Label>Workspace</Label><p className="mt-2 text-sm">{data.workspaceId || 'Sin workspace activo'}</p></div> }
function EmailStep({ data, onChange, validation }: WizardStepProps<InviteData>) { return <div className="space-y-2"><Label htmlFor="invite-email">Email</Label><Input id="invite-email" value={data.email ?? ''} onChange={(e) => onChange({ email: e.target.value })} />{validation.fieldErrors.email ? <p className="text-sm text-destructive">{validation.fieldErrors.email}</p> : null}</div> }
function RoleStep({ data, onChange, validation }: WizardStepProps<InviteData>) { return <div className="space-y-2"><Label htmlFor="invite-role">Rol</Label><Select id="invite-role" value={data.role ?? ''} onChange={(e) => onChange({ role: e.target.value })}><option value="">Selecciona un rol</option><option value="viewer">viewer</option><option value="editor">editor</option><option value="workspace_admin">workspace_admin</option></Select>{validation.fieldErrors.role ? <p className="text-sm text-destructive">{validation.fieldErrors.role}</p> : null}</div> }
function MessageStep({ data, onChange }: WizardStepProps<InviteData>) { return <div className="space-y-2"><Label htmlFor="invite-message">Mensaje</Label><Textarea id="invite-message" value={data.message ?? ''} maxLength={500} onChange={(e) => onChange({ message: e.target.value })} /></div> }
export function InviteUserWizard({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) { const { activeTenantId, activeWorkspaceId } = useConsoleContext(); const permission = useWizardPermissionCheck('invite_member'); const quota = useWizardQuotaCheck('members.count', 'workspace', activeTenantId, activeWorkspaceId); if (!permission.allowed) return open ? <ConsolePageState kind="blocked" title="Acceso bloqueado" description={permission.reason ?? 'No permitido.'} /> : null; return <WizardShell<InviteData> open={open} onOpenChange={onOpenChange} title="Invitar usuario" description="Invitación guiada de miembros al workspace activo." context={{ tenantId: activeTenantId, workspaceId: activeWorkspaceId, principalRoles: [] }} initialData={{ workspaceId: activeWorkspaceId ?? '' }} steps={[{ id: 'workspace', label: 'Workspace', component: WorkspaceStep, validate: (data) => createValidation(!data.workspaceId ? { workspaceId: 'Selecciona un workspace.' } : {}) },{ id: 'email', label: 'Email', component: EmailStep, validate: (data) => createValidation(!emailRegex.test(data.email ?? '') ? { email: 'Introduce un email válido.' } : {}, quota.available ? undefined : quota.reason ?? 'Sin cuota disponible.') },{ id: 'role', label: 'Rol', component: RoleStep, validate: (data) => createValidation(!data.role ? { role: 'Selecciona un rol.' } : {}) },{ id: 'message', label: 'Mensaje', component: MessageStep, validate: () => createValidation() }]} buildSummary={(data) => [{ label: 'Workspace', value: data.workspaceId ?? '' },{ label: 'Email', value: data.email ?? '' },{ label: 'Rol', value: data.role ?? '' },{ label: 'Mensaje', value: data.message ?? '' }]} onSubmit={async (data) => { const response = await submitWizardRequest<{ invitationId: string }>(`/v1/workspaces/${data.workspaceId ?? activeWorkspaceId}/invitations`, { email: data.email ?? '', role: data.role ?? '', message: data.message ?? '' }); return { resourceId: response.invitationId, resourceUrl: '/console/members' } }} /> }
