import { ConsolePageState } from '@/components/console/ConsolePageState'
import { WizardShell } from '@/components/console/wizards/WizardShell'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select } from '@/components/ui/select'
import { useConsoleContext } from '@/lib/console-context'
import { createValidation, submitWizardRequest, useWizardPermissionCheck, useWizardQuotaCheck, type WizardStepProps } from '@/lib/console-wizards'

interface DbData { workspaceId: string; engine: string; name: string; items: string[] }
function WorkspaceStep({ data }: WizardStepProps<DbData>) { return <div><Label>Workspace</Label><p className="mt-2 text-sm">{data.workspaceId || 'Sin workspace activo'}</p></div> }
function EngineStep({ data, onChange, validation }: WizardStepProps<DbData>) { return <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="db-engine">Motor</Label><Select id="db-engine" value={data.engine ?? ''} onChange={(e) => onChange({ engine: e.target.value, items: [] })}><option value="">Selecciona un motor</option><option value="postgresql">PostgreSQL</option><option value="mongodb">MongoDB</option></Select>{validation.blockingError ? <p className="text-sm text-destructive">{validation.blockingError}</p> : null}</div><div className="space-y-2"><Label htmlFor="db-name">Nombre</Label><Input id="db-name" value={data.name ?? ''} onChange={(e) => onChange({ name: e.target.value })} />{validation.fieldErrors.name ? <p className="text-sm text-destructive">{validation.fieldErrors.name}</p> : null}</div></div> }
function ConfigStep({ data, onChange }: WizardStepProps<DbData>) { const options = data.engine === 'postgresql' ? ['uuid-ossp','pgcrypto'] : ['users','orders']; return <div className="space-y-2"><Label>{data.engine === 'postgresql' ? 'Extensiones iniciales' : 'Colecciones iniciales'}</Label>{options.map((item) => <label key={item} className="flex items-center gap-2 text-sm"><Checkbox checked={(data.items ?? []).includes(item)} onChange={(e) => onChange({ items: e.currentTarget.checked ? [...(data.items ?? []), item] : (data.items ?? []).filter((value) => value !== item) })} />{item}</label>)}</div> }
export function ProvisionDatabaseWizard({ open, onOpenChange, defaultEngine }: { open: boolean; onOpenChange: (open: boolean) => void; defaultEngine?: 'postgresql' | 'mongodb' }) { const { activeTenantId, activeWorkspaceId } = useConsoleContext(); const permission = useWizardPermissionCheck('provision_database'); const quota = useWizardQuotaCheck('databases.count', 'workspace', activeTenantId, activeWorkspaceId); if (!permission.allowed) return open ? <ConsolePageState kind="blocked" title="Acceso bloqueado" description={permission.reason ?? 'No permitido.'} /> : null; return <WizardShell<DbData> open={open} onOpenChange={onOpenChange} title="Nueva base de datos" description="Provisioning guiado de base de datos." context={{ tenantId: activeTenantId, workspaceId: activeWorkspaceId, principalRoles: [] }} initialData={{ workspaceId: activeWorkspaceId ?? '', engine: defaultEngine ?? 'postgresql', items: [] }} steps={[{ id: 'workspace', label: 'Workspace', component: WorkspaceStep, validate: (data) => createValidation(!data.workspaceId ? { workspaceId: 'Selecciona un workspace.' } : {}) },{ id: 'engine', label: 'Motor', component: EngineStep, validate: (data) => createValidation(!data.name?.trim() ? { name: 'El nombre es obligatorio.' } : {}, quota.available ? undefined : quota.reason ?? 'Sin cuota disponible.') },{ id: 'config', label: 'Configuración', component: ConfigStep, validate: () => createValidation() }]} buildSummary={(data) => [{ label: 'Workspace', value: data.workspaceId ?? '' },{ label: 'Motor', value: data.engine ?? '' },{ label: 'Nombre', value: data.name ?? '' },{ label: 'Configuración inicial', value: (data.items ?? []).join(', ') }]} onSubmit={async (data) => { const response = await submitWizardRequest<{ databaseId: string }>(`/v1/workspaces/${data.workspaceId ?? activeWorkspaceId}/databases`, { engine: data.engine ?? defaultEngine ?? 'postgresql', name: data.name ?? '', extensions: data.engine === 'postgresql' ? data.items ?? [] : [], collections: data.engine === 'mongodb' ? data.items ?? [] : [] }); return { resourceId: response.databaseId, resourceUrl: data.engine === 'mongodb' ? '/console/mongo' : '/console/postgres' } }} /> }
