import { ConsolePageState } from '@/components/console/ConsolePageState'
import { WizardShell } from '@/components/console/wizards/WizardShell'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { useConsoleContext } from '@/lib/console-context'
import { createValidation, submitWizardRequest, useWizardPermissionCheck, useWizardQuotaCheck, type WizardStepProps } from '@/lib/console-wizards'

interface FnData { workspaceId: string; name: string; description: string; runtime: string; memoryMb: string; timeoutMs: string; route: string }
function WorkspaceStep({ data }: WizardStepProps<FnData>) { return <div><Label>Workspace</Label><p className="mt-2 text-sm">{data.workspaceId || 'Sin workspace activo'}</p></div> }
function MetaStep({ data, onChange, validation }: WizardStepProps<FnData>) { return <div className="grid gap-4"><div className="space-y-2"><Label htmlFor="fn-name">Nombre</Label><Input id="fn-name" value={data.name ?? ''} onChange={(e) => onChange({ name: e.target.value })} />{validation.fieldErrors.name ? <p className="text-sm text-destructive">{validation.fieldErrors.name}</p> : null}</div><div className="space-y-2"><Label htmlFor="fn-description">Descripción</Label><Textarea id="fn-description" value={data.description ?? ''} onChange={(e) => onChange({ description: e.target.value })} /></div></div> }
function RuntimeStep({ data, onChange, validation }: WizardStepProps<FnData>) { return <div className="grid gap-4 sm:grid-cols-3"><div className="space-y-2"><Label htmlFor="fn-runtime">Runtime</Label><Select id="fn-runtime" value={data.runtime ?? ''} onChange={(e) => onChange({ runtime: e.target.value })}><option value="">Selecciona runtime</option><option value="nodejs:18">nodejs:18</option><option value="nodejs:20">nodejs:20</option></Select>{validation.fieldErrors.runtime ? <p className="text-sm text-destructive">{validation.fieldErrors.runtime}</p> : null}</div><div className="space-y-2"><Label htmlFor="fn-memory">Memoria (MB)</Label><Input id="fn-memory" value={data.memoryMb ?? '256'} onChange={(e) => onChange({ memoryMb: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="fn-timeout">Timeout (ms)</Label><Input id="fn-timeout" value={data.timeoutMs ?? '30000'} onChange={(e) => onChange({ timeoutMs: e.target.value })} /></div></div> }
function TriggerStep({ data, onChange, validation }: WizardStepProps<FnData>) { return <div className="space-y-2"><Label htmlFor="fn-route">Ruta HTTP</Label><Input id="fn-route" value={data.route ?? ''} onChange={(e) => onChange({ route: e.target.value })} placeholder="/fn/hello" />{validation.fieldErrors.route ? <p className="text-sm text-destructive">{validation.fieldErrors.route}</p> : null}</div> }
export function PublishFunctionWizard({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) { const { activeTenantId, activeWorkspaceId } = useConsoleContext(); const permission = useWizardPermissionCheck('publish_function'); const quota = useWizardQuotaCheck('functions.count', 'workspace', activeTenantId, activeWorkspaceId); if (!permission.allowed) return open ? <ConsolePageState kind="blocked" title="Acceso bloqueado" description={permission.reason ?? 'No permitido.'} /> : null; return <WizardShell<FnData> open={open} onOpenChange={onOpenChange} title="Publicar función" description="Publicación guiada de función serverless." context={{ tenantId: activeTenantId, workspaceId: activeWorkspaceId, principalRoles: [] }} initialData={{ workspaceId: activeWorkspaceId ?? '', memoryMb: '256', timeoutMs: '30000', route: '/fn/new' }} steps={[{ id: 'workspace', label: 'Workspace', component: WorkspaceStep, validate: (data) => createValidation(!data.workspaceId ? { workspaceId: 'Selecciona un workspace.' } : {}) },{ id: 'meta', label: 'Metadatos', component: MetaStep, validate: (data) => createValidation(!data.name?.trim() ? { name: 'El nombre es obligatorio.' } : {}, quota.available ? undefined : quota.reason ?? 'Sin cuota disponible.') },{ id: 'runtime', label: 'Runtime', component: RuntimeStep, validate: (data) => createValidation(!data.runtime ? { runtime: 'Selecciona un runtime.' } : {}) },{ id: 'trigger', label: 'Trigger', component: TriggerStep, validate: (data) => createValidation(!(data.route ?? '').startsWith('/') ? { route: 'La ruta debe empezar por /.' } : {}) }]} buildSummary={(data) => [{ label: 'Workspace', value: data.workspaceId ?? '' },{ label: 'Nombre', value: data.name ?? '' },{ label: 'Descripción', value: data.description ?? '' },{ label: 'Runtime', value: data.runtime ?? '' },{ label: 'Memoria', value: data.memoryMb ?? '' },{ label: 'Timeout', value: data.timeoutMs ?? '' },{ label: 'Ruta', value: data.route ?? '' }]} onSubmit={async (data) => { const response = await submitWizardRequest<{ functionId: string }>(`/v1/workspaces/${data.workspaceId ?? activeWorkspaceId}/functions`, { name: data.name ?? '', description: data.description ?? '', runtime: data.runtime ?? '', limits: { memoryMb: Number(data.memoryMb ?? 256), timeoutMs: Number(data.timeoutMs ?? 30000) }, trigger: { kind: 'http', route: data.route ?? '/fn/new' } }); return { resourceId: response.functionId, resourceUrl: '/console/functions' } }} /> }
