import { collectObservedUsage } from '../repositories/tenant-usage-snapshot-repository.mjs';
import { evaluateQuotaDecision } from '../models/quota-enforcement.mjs';
import { resolveEffectiveLimit, insertEnforcementLog } from '../repositories/quota-enforcement-repository.mjs';
import { emitEnforcementEvent } from '../events/quota-enforcement-events.mjs';
export async function main(params={}, overrides={}) { const db=overrides.db??params.db; const producer=overrides.producer??params.producer; const effective=await resolveEffectiveLimit(db, params.tenantId, params.dimensionKey); let currentUsage=params.currentUsage; if (currentUsage === undefined) { const observed = await collectObservedUsage(params.tenantId, [params.dimensionKey], { client: db, collectors: params.collectors }); currentUsage = observed[0]?.observedUsage; }
  const decision=evaluateQuotaDecision({ effectiveLimit:effective.effectiveLimit, quotaType:effective.quotaType, graceMargin:effective.graceMargin, currentUsage }); const response={ ...decision, source:effective.source, effectiveLimit:effective.effectiveLimit, quotaType:effective.quotaType, graceMargin:effective.graceMargin, effectiveCeiling:decision.effectiveCeiling, currentUsage:decision.currentUsage };
  await insertEnforcementLog(db,{ tenantId:params.tenantId, workspaceId:params.workspaceId ?? null, dimensionKey:params.dimensionKey, attemptedAction:params.attemptedAction ?? null, currentUsage:decision.currentUsage ?? null, effectiveLimit:effective.effectiveLimit, quotaType:effective.quotaType, graceMargin:effective.graceMargin, effectiveCeiling:decision.effectiveCeiling ?? effective.effectiveCeiling, source:effective.source, decision:decision.decision, actorId:params.callerContext?.actor?.id ?? null, correlationId:params.correlationId ?? null, warning:decision.warning ?? null });
  if (decision.decision === 'metering_unavailable') throw Object.assign(new Error('Metering unavailable'), { code:'METERING_UNAVAILABLE', statusCode:500, body: response });
  await emitEnforcementEvent(producer, decision.decision, { tenantId:params.tenantId, workspaceId:params.workspaceId ?? null, dimensionKey:params.dimensionKey, payload:{ currentUsage:decision.currentUsage, effectiveLimit:effective.effectiveLimit, effectiveQuotaType:effective.quotaType, source:effective.source, decision:decision.decision, attemptedAction:params.attemptedAction ?? null } });
  return { statusCode:200, body:response, headers: decision.decision === 'soft_grace_allowed' ? { 'X-Quota-Warning': decision.warning } : {} };
}
