routes:
  - name: control-plane-webhooks
    uri: /v1/webhooks/*
    priority: 100
    methods: [GET, POST, PATCH, DELETE]
    plugins:
      keycloak-openid:
        client_id: control-plane
        bearer_only: true
    upstream:
      type: roundrobin
      nodes:
        "falcone-control-plane.falcone.svc.cluster.local:8080": 1
