import test from 'node:test';
import assert from 'node:assert/strict';
import { CaptureConfigRepository } from '../../../src/repositories/realtime/CaptureConfigRepository.mjs';
const makeClient = ({ workspaceCurrent = 0, workspaceQuota = 10, tenantCurrent = 0, tenantQuota = 50, insertRow = { id: '1', tenant_id: 't', workspace_id: 'w', data_source_ref: 'db', schema_name: 'public', table_name: 'orders', actor_identity: 'u', status: 'active' } } = {}) => ({
  queries: [],
  async query(sql) { this.queries.push(sql); if (sql.includes("scope='workspace'")) return { rows: [{ quota: workspaceQuota, current: workspaceCurrent }] }; if (sql.includes("scope='tenant'")) return { rows: [{ quota: tenantQuota, current: tenantCurrent }] }; if (sql.includes('INSERT INTO pg_capture_configs')) return { rows: insertRow ? [insertRow] : [] }; if (sql.includes('SELECT * FROM pg_capture_configs WHERE data_source_ref')) return { rows: [insertRow, { ...insertRow, id: '2', status: 'disabled' }] }; if (sql.includes('SELECT * FROM pg_capture_configs WHERE tenant_id=$1 AND workspace_id=$2 AND ($3::text IS NULL OR status=$3)')) return { rows: [insertRow] }; if (sql.includes('SELECT * FROM pg_capture_configs WHERE tenant_id=$1 AND workspace_id=$2 AND id=$3')) return { rows: [insertRow] }; if (sql.includes('UPDATE pg_capture_configs')) return { rows: [{ ...insertRow, status: 'disabled', deactivation_ts: 'now' }] }; if (sql.includes('GROUP BY workspace_id')) return { rows: [{ workspace_id: 'w', active_count: 1, tables: [] }] }; return { rows: [] }; },
  release() {}
});
const wrapPool = (client) => ({ connect: async () => client, query: (...args) => client.query(...args) });
const attrs = { tenant_id: 't', workspace_id: 'w', data_source_ref: 'db', table_name: 'orders', actor_identity: 'u' };
test('create inserts record', async () => { const repo = new CaptureConfigRepository(wrapPool(makeClient())); const row = await repo.create(attrs); assert.equal(row.table_name, 'orders'); });
test('create throws workspace quota', async () => { const repo = new CaptureConfigRepository(wrapPool(makeClient({ workspaceCurrent: 10, workspaceQuota: 10 }))); await assert.rejects(() => repo.create(attrs), (err) => err.code === 'QUOTA_EXCEEDED' && err.scope === 'workspace'); });
test('create throws tenant quota', async () => { const repo = new CaptureConfigRepository(wrapPool(makeClient({ tenantCurrent: 50, tenantQuota: 50 }))); await assert.rejects(() => repo.create(attrs), (err) => err.code === 'QUOTA_EXCEEDED' && err.scope === 'tenant'); });
test('create idempotent returns existing active record', async () => { const repo = new CaptureConfigRepository(wrapPool(makeClient())); const a = await repo.create(attrs); const b = await repo.create(attrs); assert.equal(a.id, b.id); });
test('concurrent create quota simulated exactly N succeed', async () => { let count = 0; const client = makeClient({}); client.query = async (sql) => { if (sql.includes("scope='workspace'")) return { rows: [{ quota: 5, current: count }] }; if (sql.includes("scope='tenant'")) return { rows: [{ quota: 50, current: count }] }; if (sql.includes('INSERT INTO pg_capture_configs')) { count += 1; return count <= 5 ? { rows: [{ id: String(count), ...attrs, schema_name: 'public', status: 'active' }] } : { rows: [] }; } return { rows: [] }; }; const repo = new CaptureConfigRepository(wrapPool(client)); const results = await Promise.allSettled(Array.from({ length: 10 }, (_, i) => repo.create({ ...attrs, table_name: `orders_${i}` }))); assert.equal(results.filter((r) => r.status === 'fulfilled').length, 5); });
test('findActive returns active rows', async () => { const repo = new CaptureConfigRepository(wrapPool(makeClient())); const rows = await repo.findActive('db'); assert.equal(rows.length, 2); });
test('findByWorkspace filters', async () => { const repo = new CaptureConfigRepository(wrapPool(makeClient())); const rows = await repo.findByWorkspace('t', 'w'); assert.equal(rows.length, 1); });
test('disable sets disabled', async () => { const repo = new CaptureConfigRepository(wrapPool(makeClient())); const row = await repo.disable('1', 'u'); assert.equal(row.status, 'disabled'); });
